#!name=ChatAI
#!desc=chatai解锁vip

[Script]

chatai_8 = type=http-response, pattern=^https?:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/?(.*?)*$), requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/Revenuecat/chatai.js, timeout=60, script-update-interval=0

chatai_9 = type=http-request, pattern=^https?:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/?(.*?)*$), script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/Revenuecat/chatai.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% api.revenuecat.com
