#!name=getCookies
#!desc=获取cookies

[Script]

JD_DailyBonus_6 = type=http-request, pattern=^https:\/\/(api\.m|me-api)\.jd\.com\/(client\.action\?functionId=signBean|user_new\/info\/GetJDUserInfoUnion\?), script-path=https://raw.githubusercontent.com/chxm1023/Task/main/JD/JD_DailyBonus.js, timeout=60, script-update-interval=0

#TieBa_9 = type=http-request, pattern=^https?:\/\/tiebac\.baidu\.com\/c\/u\/follow\/getFoldedMessageUserInfo, script-path=https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/TieBa.js, timeout=60, script-update-interval=0
# ^https?:\/\/tiebac\.baidu\.com\/c\/u\/follow\/getFoldedMessageUserInfo url script-request-header https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/TieBa.js
#TieBa_10 = type=http-request, pattern=^https?:\/\/c\.tieba\.baidu\.com\/c\/u\/follow\/getFoldedMessageUserInfo, script-path=https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/TieBa.js, timeout=60, script-update-interval=0
# ^https?:\/\/c\.tieba\.baidu\.com\/c\/u\/follow\/getFoldedMessageUserInfo url script-request-header https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/TieBa.js
tieba_signin_11 = type=http-request, pattern=^https?:\/\/(c\.tieba\.baidu\.com|180\.97\.\d+\.\d+)\/c\/s\/login, script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/tieba/tieba_signin.js, timeout=60, script-update-interval=0

tieba_signin_12 = type=http-request, pattern=^https?:\/\/c\.tieba\.baidu\.com\/c\/s\/channelIconConfig, script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/tieba/tieba_signin.js, timeout=60, script-update-interval=0

tieba_signin_13 = type=http-request, pattern=^https?:\/\/tiebac\.baidu\.com\/c\/u\/follow\/getFoldedMessageUserInfo, script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/tieba/tieba_signin.js, timeout=60, script-update-interval=0

#aliYunPanCheckIn_16 = type=http-response, pattern=^https:\/\/auth.aliyundrive.com\/v2\/account\/token, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/lowking/Scripts/master/ali/aliYunPanCheckIn.js, timeout=60, script-update-interval=0
aliYunPanCheckIn_18 = type=http-response, pattern=^https:\/\/auth.(aliyundrive|alipan).com\/v2\/account\/token, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/lowking/Scripts/master/ali/aliYunPanCheckIn.js, timeout=60, script-update-interval=0

BiliBili_21 = type=http-request, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/domain\?, script-path=https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/BiliBili.js, timeout=60, script-update-interval=0

BiliBili_22 = type=http-request, pattern=^https?:\/\/m.bilibili.com/$, script-path=https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/BiliBili.js, timeout=60, script-update-interval=0

bingPoint_26 = type=http-request, pattern=^https:\/\/rewards\.bing\.com, script-path=https://raw.githubusercontent.com/lowking/Scripts/master/bing/bingPoint.js, timeout=60, script-update-interval=0

jhsh_checkIn_29 = type=http-request, pattern=^https:\/\/yunbusiness\.ccb\.com\/clp_coupon\/txCtrl\?txcode=A3341A040, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/jhsh_checkIn.js, timeout=60, script-update-interval=0

qidian.cookie_32 = type=http-request, pattern=https\:\/\/h5\.if\.qidian\.com\/argus\/api\/v1\/video\/adv\/finishWatch, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/MCdasheng/QuantumultX/main/Scripts/myScripts/qidian/qidian.cookie.js, timeout=60, script-update-interval=0

qidian.taskId_33 = type=http-response, pattern=https\:\/\/h5\.if\.qidian\.com\/argus\/api\/v1\/video\/adv\/mainPage, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/MCdasheng/QuantumultX/main/Scripts/myScripts/qidian/qidian.taskId.js, timeout=60, script-update-interval=0

ampDache_40 = type=http-response, pattern=^https:\/\/m5(-zb)?\.amap\.com\/ws\/yuece\/(act|openapi)\/(activity\/current\/)?query, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/wf021325/qx/master/task/ampDache.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% ms.jr.jd.com,me-api.jd.com,api.m.jd.com,tiebac.baidu.com,c.tieba.baidu.com,auth.alipan.com,*.bilibili.com,rewards.bing.com,yunbusiness.ccb.com,h5.if.qidian.com,*.amap.com
