#!name=Spotify
#!desc=Spotify
#!author=ddgksf2013

[Script]

spotify-proto_11 = type=http-response, pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$, requires-body=true, max-size=3145728, binary-body-mode=true, script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js, timeout=60, script-update-interval=0

spotify-json_12 = type=http-request, pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/, script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% spclient.wg.spotify.com
